# Generated by Django 4.2.5 on 2023-09-09 12:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simplesshkey', '0004_auto_20180325_1420'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userkey',
            unique_together={('user', 'fingerprint')},
        ),
    ]
