# Generated by Django 4.2.5 on 2023-09-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplesshkey', '0005_alter_userkey_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='fingerprint',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
